import vertexai
from vertexai.generative_models import GenerativeModel

PROJECT_ID = "your-project-id"
LOCATION = "us-central1"

vertexai.init(project="real-estate-490304", location="global")

# IMPORTANT: Use the same agent model you showed me
agent_model = GenerativeModel(
    "gemini-2.5-flash",
    tools=[combined_tool],   # your unified tool
    generation_config={
        "max_output_tokens": 2048,
        "temperature": 0.2,
    }
)


def ask_llm(prompt):
    """
    Sends a prompt to the Gemini agent model and returns:
    - Final text answer if available
    - Tool call details if the model triggers a tool
    """

    response = agent_model.generate_content(
        prompt,
        stream=False
    )

    # CASE 1 — Model produced normal text
    if response.text:
        return response.text

    # CASE 2 — Model triggered a tool call
    if response.candidates:
        parts = response.candidates[0].content.parts
        return str(parts)

    # CASE 3 — Nothing returned
    return "No response generated by the model."
